CREATE TABLE IF NOT EXISTS plague_quests (
  citizenid VARCHAR(64) NOT NULL,
  quest_id VARCHAR(64) NOT NULL,
  stage INT NOT NULL DEFAULT 0,
  flags_json LONGTEXT NOT NULL DEFAULT '{}',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (citizenid, quest_id)
);
